[package]
name = "twod-platformer-sandbox"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.57"
bevy = "0.7.0"
bevy_asset_loader = { version = "0.10.0", features = ["2d"] }
bevy_ecs_tilemap = "0.6.0"
iyes_loopless = "0.5.1"
ldtk_rust = "0.5.3"
serde = "1.0.136"
serde_json = "1.0.79"
